[package]
name = "tss-esapi"
version = "7.1.0"
authors = ["Parsec Project Contributors"]
edition = "2018"
description = "Rust-native wrapper around TSS 2.0 Enhanced System API"
readme = "README.md"
keywords = ["tpm", "tss", "esys", "esapi"]
categories = ["api-bindings", "external-ffi-bindings", "cryptography"]
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/rust-tss-esapi"
documentation = "https://docs.rs/crate/tss-esapi"

[dependencies]
bitfield = "0.13.2"
serde = { version = "1.0.115", features = ["derive"] }
mbox = "0.6.0"
log = "0.4.11"
enumflags2 = "0.7.7"
num-derive = "0.3.2"
num-traits = "0.2.12"
hostname-validator = "1.1.0"
regex = "1.3.9"
zeroize = { version = "1.5.7", features = ["zeroize_derive"] }
tss-esapi-sys = { path = "../tss-esapi-sys", version = "0.4.0" }
oid = { version = "0.2.1", optional = true }
picky-asn1 = { version = "0.3.0", optional = true }
picky-asn1-x509 = { version = "0.6.1", optional = true }
cfg-if = "1.0.0"
strum = { version = "0.25.0", optional = true }
strum_macros = { version = "0.25.0", optional = true }

[dev-dependencies]
env_logger = "0.9.0"
sha2 = "0.10.1"

[build-dependencies]
semver = "1.0.7"

[features]
default = ["abstraction"]
generate-bindings = ["tss-esapi-sys/generate-bindings"]
abstraction = ["oid", "picky-asn1", "picky-asn1-x509"]
integration-tests = ["strum", "strum_macros"]
